<?php

namespace AppBundle\Repository\Like;

/**
 * LikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return object
     */
    public function FindLikePostOnUser($post, $user)
    {

        return $this->findBy(array('post' => $post, 'user'=>$user));
    }
}
