<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findApprovedOrderByDesc()
    {
        return $this->createQueryBuilder('post')
            ->where('post.isApproved = true')
            ->orderBy('post.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function search($param)
    {
        return $this->createQueryBuilder('post')
            ->andWhere('post.title LIKE :param')
            ->orWhere('post.text LIKE :param')
            ->setParameter(':param', '%'.$param.'%')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findNotApprovedPosts()
    {
        return $this->createQueryBuilder('post')
            ->where('post.isApproved = false')
            ->orderBy('post.id', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }
}
