<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($param)
    {
        return $this->createQueryBuilder('user')
            ->andWhere('user.username LIKE :param')
            ->orWhere('user.firstName LIKE :param')
            ->orWhere('user.lastName LIKE :param')
            ->setParameter(':param', '%'.$param.'%')
            ->getQuery()
            ->getResult();
    }
}
