# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.paginateManager.limit : 3

services:
  app.form_manager:
        class: AppBundle\Services\FormManager
        arguments: ["@doctrine", "@form.factory"]
  app.paginate_manager:
        class: AppBundle\Services\PaginateManager
        arguments: ['%app.paginateManager.limit%']
