# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.notifier:
          class:        AppBundle\Services\Notifier
          arguments: ['@mailer', '@logger', '@session.flash_bag']

  app.form_manager:
          class:        AppBundle\Services\Forms
          arguments: ['@form.factory', '@doctrine', '@router', '@app.notifier']
  app.twig_extension:
          class: AppBundle\Twig\AppExtension
          tags:
              - { name: twig.extension }