# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    app.brochure_uploader:
            class: AppBundle\Services\FileUploader
            arguments: ['%images_directory%']

    app.form_manager:
        class:        AppBundle\Services\Forms
        arguments: ['@form.factory', '@doctrine', '@router', '@app.brochure_uploader']


