# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.pgManager.limit : 3
    img_upload_directory : %kernel.root_dir%/../web/images

services:
     app.dbManager:
            class: AppBundle\Services\DataBaseManager
            arguments: ["@doctrine.orm.entity_manager"]
     app.pgManager:
            class: AppBundle\Services\PaginateManager
            arguments: ['%app.pgManager.limit%']
     app.twig_extension:
            class: AppBundle\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }
     app.user_voter:
             class: AppBundle\Security\UserVoter
             arguments: ['@security.access.decision_manager']
             tags:
                 - { name: security.voter }
             public: false
     app.file_uploader:
             class: AppBundle\Services\FileUploadManager
             arguments: ['%img_upload_directory%']
     app.doctrine_img_listener:
             class: AppBundle\EventListener\DataBaseListener
             arguments: ['@app.file_uploader', '@security.password_encoder']
             tags:
                  - { name: doctrine.event_listener, event: prePersist }
                  - { name: doctrine.event_listener, event: preUpdate }
                  - { name: doctrine.event_listener, event: postLoad }
