# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  model.service:
    class: AppBundle\Model\NewsModel
    arguments: ["@doctrine.orm.entity_manager"]