# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.form_manager:
        class: AppBundle\Services\FormManager
        arguments: ["@doctrine", "@form.factory"]
