# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    service_saved_input_value:
        class: AppBundle\Services\SavedInputForm

    twig.extension.greeting:
              class: AppBundle\Twig\GreetingHolidays
              public: true
              tags:
                  - { name: twig.extension }

    #app.exception_listener:
    #        class: AppBundle\EventListener\ExceptionListener
    #        tags:
    #            - { name: kernel.event_listener, event: kernel.exception }

    app.request_listener:
                class: AppBundle\EventListener\AjacsRequestListener
                tags:
                   - { name: kernel.event_listener, event: kernel.request }