# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.pgManager.limit : 3

services:
     app.dbManager:
            class: AppBundle\Services\DataBaseManager
            arguments: ["@doctrine.orm.entity_manager"]
     app.pgManager:
            class: AppBundle\Services\PaginateManager
            arguments: ['%app.pgManager.limit%']
     app.twig_extension:
            class: AppBundle\Twig\AppExtension
            public: false
            tags:
                - { name: twig.extension }